name: Run Tests

on:
  workflow_call:
    inputs:
      slow-tests:
        type: boolean
        default: false
      python-version:
        type: string
        required: true
      exasol-version:
        type: string
        required: true

jobs:

  tests-job:
    name: Run Tests (Python-${{ inputs.python-version }})
    runs-on: ubuntu-latest

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v4

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.14.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run Unit Tests
        if: ${{ ! inputs.slow-tests }}
        run:
          poetry run nox -s test:unit

      - name: Run Integration Tests
        if: ${{ inputs.slow-tests }}
        env:
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}
        run:
          poetry run nox -s test:integration -- -- --db-version ${{ inputs.exasol-version}} --backend all
