name: Slow-Checks-SaaS

on:
  workflow_call:

jobs:
  run-integration-tests:
    name: Run Integration Tests with SaaS (Python-3.12)
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read

    steps:
      - name: Allow unprivileged user namespaces
        id: allow-unprivileged-user-namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Check out Repository
        id: check-out-repository
        uses: actions/checkout@v6

      - name: Set up Python & Poetry Environment
        id: set-up-python-and-poetry-environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v8
        with:
          python-version: "3.12"
          poetry-version: "2.3.0"

      - name: Run Integration Tests
        id: run-integration-tests
        run: >
          poetry run -- nox -s test:integration -- -s --coverage
          --backend=saas
        env:
          SAAS_HOST: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_HOST }}
          SAAS_ACCOUNT_ID: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID }}
          SAAS_PAT: ${{ secrets.INTEGRATION_TEAM_SAAS_STAGING_PAT }}

      - name: Upload Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v7
        with:
          name: coverage-python3.12-slow-saas
          path: .coverage
          include-hidden-files: true
